eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:8090/realms/paideia}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8090/realms/paideia/protocol/openid-connect/certs}
          
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  otlp:
    metrics:
      export:
        enabled: false
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_TRACES_ENDPOINT:http://127.0.0.1:4318/v1/traces}
    logging:
      export:
        otlp:
          endpoint: ${OTEL_LOGS_ENDPOINT:http://127.0.0.1:4318/v1/logs}
        schedule-delay: 1s
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    io.paideia: INFO
  pattern:
    correlation: "[traceId=%X{traceId:-},spanId=%X{spanId:-}] "