spring:
  servlet:
    multipart:
      max-file-size: ${CONTENT_MAX_FILE_SIZE:5MB}
      max-request-size: ${CONTENT_MAX_REQUEST_SIZE:6MB}
  mongodb:
    uri: ${CONTENT_MONGODB_URI:mongodb://localhost:27017/content}
    representation:
      uuid: standard

server:
  port: ${CONTENT_SERVICE_PORT:8085}

paideia:
  seed:
    content:
      enabled: ${CONTENT_SEED_ENABLED:true}

clients:
  enrollment-service:
    url: ${ENROLLMENT_SERVICE_URL:http://localhost:8082}