<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.paideia</groupId>
    <artifactId>paideia-poc-microservices-spring</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>paideia-poc-microservices-spring</name>
    <description>POC para aprender microservicios con el ecosistema de Spring</description>

    <modules>
        <module>services/course-service</module>
        <module>services/enrollment-service</module>
        <module>services/payment-service</module>
        <module>services/user-service</module>
        <module>services/notification-service</module>
        <module>services/content-service</module>
    </modules>

</project>
