spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: course-service
              uri: lb://course-service
              predicates:
                - Path=/courses/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
            - id: enrollment-service
              uri: lb://enrollment-service
              predicates:
                - Path=/enrollments/**
            - id: content-service
              uri: lb://content-service
              predicates:
                - Path=/contents/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notifications/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payments/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,prometheus
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces

  tracing:
    sampling:
      probability: 1.0